### ISSUE TITLE
google api DF-DFERH-01

### ISSUE THREAD

**Issue by hojyh1** [Dynamic-Mobile-Security/mdast-cli#102]
Hi, I'm using the library well, but an error occurred, so I'm posting an issue

DF-DFERH-01 error occurs when calling Google Purchase api if the vc parameter is None
So if there is no vc value, I think it would be better to delete the vc parameter when requesting api.

https://github.com/Dynamic-Mobile-Security/mdast-cli/blob/main/mdast_cli/distribution_systems/gpapi/googleplay.py#L159

Note) 
* vc=None
<pre><code>[ HTTP Request ]
POST /fdfe/purchase HTTP/2
Host: android.clients.google.com
...

ot=1&#38;doc=net.daum.android.webtoon&#38;vc=None

[ HTTP Response ]
HTTP/2 400 Bad Request
Content-Type: application/protobuf
...

VT&#49436;&#48260;&#50640;&#49436; &#51221;&#48372;&#47484; &#44032;&#51256;&#50724;&#45716; &#51473;&#50640; &#50724;&#47448;&#44032; &#48156;&#49373;&#54664;&#49845;&#45768;&#45796;. DF-DFERH-01</code></pre>
* Remove vc parameters
<pre><code>[ HTTP Request ]
POST /fdfe/purchase HTTP/2
Host: android.clients.google.com
...

ot=1&#38;doc=net.daum.android.webtoon

[ HTTP Response ]
HTTP/2 200 OK
Content-Type: application/protobuf
...

&#65533;&#34;&#65533;
&#65533;s2m&#1632;&#680;&#590;A&#65533;D&#65533;A&#34;S

net.daum.android.webtoon&#65533;&#65533;&#65533;&#65533;&#436;&#65533;&#65533;&#65533;*Qm7e1b_eHr14u31lGLoJX8oR5NE`&#65533;&#65533;&#65533;&#65533;&#65533;123B&#65533;:26 
net.daum.android.webtoon *KRW&#65533;&#65533;wAB-xQnrBZw3LWDVGNqFvmCMVlL7tBp0IO3cC0jF5YfyrssafDOXjs5_XXPakcAYNH0TefJ6k9qYzAK8ezDBT2bY79swRm65RaaCmehFdJ6c4OrAz-9fpSdc&#65533;wAB-xQnrxL6GHZWE0qzrV8osXNNoyYc5yQBINKSoaIcTyiR0fT1cIGmfWHO5dCBEG4r_hP_H9upgsCLJ3UPJgYnGwyuNVawN1w3anotGZT9_oknD7PDWZz3E*&#65533;J&#65533;
&#65533;&#65533;&#65533;&#65533;&#65533;&#449;&#662;
H&#65533;&#65533;</code></pre>

**Comment by hahwul** [comment]
Hi team 👋🏼 
I'm experiencing a similar issue. I think that handling the `vc` parameters might be necessary. 
If you ever need help with testing or anything else, please let me know. I'll be happy to actively support you :D

**Comment by npinaev** [comment]
Hi @hojyh1 @hahwul!

Thanks for this issue. We are very grateful for the idea and pr. Sorry for the long response by the way

I checked it out, pr works, but in this tool we use slightly different logic with python cli arguments, so I implement this fix in PR: #105 #106

Now if you use optional parameter '--google_play_vc_null' while running script, param['vc'] will be excluded. Works from 2023.10.3 tag

example: 
mdast_cli -d --ds google_play --google_play_email mail --google_play_password pass --google_play_download_with_creds
 --google_play_package_name net.daum.android.webtoon --google_play_vc_null
