### ISSUE TITLE
images

### ISSUE THREAD

**Issue by NPinaev** [Dynamic-Mobile-Security/mdast-cli#11]
![Screenshot 2022-01-17 at 07 04 54](https://user-images.githubusercontent.com/46852358/149773186-2509d5da-e245-4da5-9eb0-2499afd9bbcd.png)

**Comment by NPinaev** [comment]
![image](https://user-images.githubusercontent.com/46852358/149788352-d453dd78-547f-4989-8132-b94a6f020a81.png)

**Comment by NPinaev** [comment]
![image](https://user-images.githubusercontent.com/46852358/149789837-2787cb52-355d-4ef0-9440-89053764db78.png)

**Comment by NPinaev** [comment]
![image](https://user-images.githubusercontent.com/46852358/149791304-2658f1be-9ee0-422e-94ce-59f1ba1858df.png)

**Comment by NPinaev** [comment]
![image](https://user-images.githubusercontent.com/46852358/149792212-512d33ab-2323-45b6-a25c-6a8d817cde1f.png)

**Comment by NPinaev** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/46852358/153638449-6488cf6d-214f-44cb-8265-fe8b79b2614f.png">

**Comment by NPinaev** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/46852358/153639003-f121273a-41ac-415d-aad7-6b2789f77cee.png">

**Comment by NPinaev** [comment]
![apple_id_wrong](https://user-images.githubusercontent.com/46852358/158440208-45868069-d772-4476-a1bf-6508c2bac1eb.jpg)

**Comment by NPinaev** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46852358/161290143-05d0d847-2037-4c4f-8187-53d3ffed83ec.png">

**Comment by NPinaev** [comment]
![Screenshot 2022-04-11 at 19 51 36](https://user-images.githubusercontent.com/46852358/162791052-fbce7121-1430-49ca-a9b9-68997391abd6.png)

**Comment by npinaev** [comment]
<img width="327" alt="Screenshot 2022-12-28 at 03 54 55" src="https://user-images.githubusercontent.com/46852358/209744381-66bd117a-c16e-40d2-9d24-fc0b694a912d.png">
