### ISSUE TITLE
How to find firebase app code ?

### ISSUE THREAD

**Issue by rakeshkarkare** [Dynamic-Mobile-Security/mdast-cli#22]
How to find firebase app code ?

**Comment by npinaev** [comment]
Hey @rakeshkarkare! You can find it in download url:

`https://firebaseappdistribution-pa.clients6.google.com/v1/projects/{project_id}/apps/{app_id}/releases/{**app_code**}:getLatestBinary?alt=json&key={api_key}
`

**Comment by Rakeshkarkare20** [comment]
Hi @npinaev , 

I want to automate the firebase download build for that I need to understand how can I get APP_CODE at runtime for particular build

**Comment by rakeshkarkare** [comment]
Hi @npinaev ,

I want to automate the firebase download build for that I need to understand how can I get APP_CODE at runtime for particular build

**Comment by npinaev** [comment]
Hi@rakeshkarkare, sorry for long response
 I think it's not possible, unfortunately. APP_CODE looks like a random string, so you should manually extract it from web interface. I researched a bit for this issue and didn't come up with a working solution.

**Comment by rakeshkarkare** [comment]
Hi @npinaev , 

Thanks for the reply do let me know If you're able to find any solution

**Comment by kaibolay** [comment]
@npinaev,

The [public REST API](https://firebase.google.com/docs/reference/app-distribution/rest) can (now) be used to get the download URL. See `binaryDownloadUri` in the [Release](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.apps.releases#Release) resource.

You could [list](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.apps.releases/list) all releases for a given `app_id` (or pick the latest release using `orderBy: createTime desc` and `pageSize: 1` to get the latest release).

**Comment by npinaev** [comment]
@kaibolay thanks a lot! I'll check it
